apiVersion: v1
kind: Service
metadata:
  name: cropdarpan-frontend-service
spec:
  selector:
    app: cropdarpan-frontend
  ports:
  - protocol: TCP
    port: 80 # The port the service will listen on
    targetPort: 80 # The port on the container to forward traffic to
  type: LoadBalancer # Exposes the service with an external IP in cloud environments